### ISSUE TITLE
problem with presenting alert

### ISSUE THREAD

**Issue by hacik81** [leonardsangoroh/GuessTheFlag#1]
// You have 3 buttons so should use random from 0 (0, 1, 2)
        correctAnswer = Int.random(in: 0...2)

    @IBAction func buttonTapped(_ sender: UIButton) {
        
        var title:String
         //check whether answer is correct
        //Count score
        if sender.tag == correctAnswer {
            title = "CORRECT"
            score += 1
        } else {
            title = "WRONG"
            score -= 1
        }
        
        //send an alert showing what the new score is
        let ac = UIAlertController(title: title, message: "Your score is \(score)", preferredStyle: .alert)
        //Setting continue button on the alert
        ac.addAction(UIAlertAction(title: "Continue", style: .default, handler: askQuestion))
        
        // You forgot to present alert
        present(ac, animated: true)
    }

**Comment by leonardsangoroh** [comment]
Hi @hacik81, thanks for helping resolve the presentation bug. I appreciate it, thanks!

**Comment by leonardsangoroh** [comment]
Could you be knowing why my flags are not properly fitting into the button borders?

**Comment by leonardsangoroh** [comment]
Could you be knowing why my flags are not properly fitting into the button borders?

**Comment by hacik81** [comment]
<img width="262" alt="Zrzut ekranu 2023-04-6 o 10 35 19" src="https://user-images.githubusercontent.com/43092885/230322220-162b2b15-073c-4f1f-9d41-43f0ad2f478a.png">

**Comment by leonardsangoroh** [comment]
@hacik81 thanks a lot, the issue has been resolved.
